### ISSUE TITLE
Feature Request: add a setting for a custom default weight for the pathing grid

### ISSUE THREAD

**Issue by Jensiii666** [eladyaniv01/SC2MapAnalysis#44]
Currently you mark "bad things" on influence map, but setting a higher default weight would also allow marking "good things" on the influence map, so we can tell the pathing to "prefer this".

**Copy pasted discord conversation as a note:**

_jensiiiToday at 6:33 PM
What if I want to mark good things on the map? :smile:
EladYaniv01Today at 6:33 PM
ok i see what you mean
jensiiiToday at 6:33 PM
That's basically my question
EladYaniv01Today at 6:33 PM
hold on
jensiiiToday at 6:33 PM
:smile:
EladYaniv01Today at 6:34 PM
you can take the grid that the lib returns (get_pyastar_grid)
and do
CUSTOM_DEFAULT_WEIGHT = 300
grid = np.where(grid == 1, CUSTOM_DEFAULT_WEIGHT, np.inf).astype(np.float32)
it will switch all 1's to 300
and leave the np.inf for non pathable_

**Comment by eladyaniv01** [comment]
https://github.com/eladyaniv01/SC2MapAnalysis/blob/master/MapAnalyzer/MapData.py#L89
Done!
