### ISSUE TITLE
Feature request: Pathfinding through regions

### ISSUE THREAD

**Issue by raspersc2** [eladyaniv01/SC2MapAnalysis#51]
Regular path finding via the pyastar lib works well, but it would also be useful to calculate paths through the regions this library calculates, where each point in the path is perhaps the center location of the interconnected region.

This could be a far more efficient way to calculate a path for many use cases, while pathfinding via the pyastar lib is most useful when precise movements are required. Some use cases I can think of, but there are probably more:

- Routing an army around the edge of the map
- Routing an army while avoiding a particular region the enemy currently occupies (avoiding regions with influence?)
- Find all available paths from a start region to the target region
- Find path to region while avoiding a certain choke / ramp

**Comment by eladyaniv01** [comment]
Done! 
https://github.com/eladyaniv01/SC2MapAnalysis/blob/master/CHANGELOG.md#issues-closed
