### ISSUE TITLE
Feature request: get dead airspace from map analyzer

### ISSUE THREAD

**Issue by Jensiii666** [eladyaniv01/SC2MapAnalysis#53]
Get dead airspace from map analyzer. Maybe even group it to regions of dead airspace, so one could use that to navigate to specific areas of dead space in the map.

**Comment by eladyaniv01** [comment]
I see two use cases here :
*  flying unit micro,  abusing un-pathable terrain vs ground units
* generating smart pathing for fly units with influence map,  like you suggested - through " air regions"  

Anything else?

**Comment by Jensiii666** [comment]
Nothing that doesn't already go under the categories you mentioned..

The knowledge of dead air space can also be used to defend against all that you mentioned I suppose ie. building a turret towards dead air space or spotter depot or having units camp the direction of a dead air space (like stalkers have to stay at home vs the threath of a widow mine drop, sitting in the dead air space in human games)

**Comment by eladyaniv01** [comment]
https://github.com/eladyaniv01/SC2MapAnalysis/blob/master/CHANGELOG.md#issues-closed
