### ISSUE TITLE
clean_air_grid size is bigger than playable area size, so pather with try to path to areas where units can't go

### ISSUE THREAD

**Issue by Jensiii666** [eladyaniv01/SC2MapAnalysis#73]
![image](https://user-images.githubusercontent.com/68125074/91635956-6052da00-ea05-11ea-8948-deedd7ece3ee.png)

**Comment by eladyaniv01** [comment]
https://github.com/eladyaniv01/SC2MapAnalysis/commit/53dd07a1d82eefbe5656f71d782015daa98b19f5
