### ISSUE TITLE
Feature request: find lowest influence / cost within a radius

### ISSUE THREAD

**Issue by raspersc2** [eladyaniv01/SC2MapAnalysis#78]
It's sometimes useful to find the "safest" position for a unit within a restricted radius. For example, a unit kiting while its weapon is on call down. Example method signature:

`def self.find_lowest_cost(self, from_pos: Point2, radius: int, grid: np.ndarray) -> Point2:`

**Comment by eladyaniv01** [comment]
I have been toying around with the idea,  and the biggest issue i see right now is how to decide which of the evenly low-cost points should we pick? 
perhaps a better approach would be to return a list of all low influence points in that radius, and let the user decide how to proceed?

**Comment by eladyaniv01** [comment]
https://github.com/eladyaniv01/SC2MapAnalysis/commit/73c2251af2cf52b533f7082886a348263e7c4884

**Comment by raspersc2** [comment]
Thanks for implementing this feature. 

I think that's a good idea, for many use-cases picking the first element in the list may suffice. But I agree, returning all the low cost positions opens up more opportunity.
